use "std/test"
use "std/regex"

test.module("Regex Functions")

test.describe("regex.match", fun ()
    test.it("matches simple patterns", fun ()
        test.assert_eq(regex.match("hello", "hello world"), true)
        test.assert_eq(regex.match("hello", "goodbye"), false)
    end)

    test.it("matches regex patterns", fun ()
        test.assert_eq(regex.match("\\d+", "abc123"), true)
        test.assert_eq(regex.match("^\\d+$", "123"), true)
        test.assert_eq(regex.match("^\\d+$", "abc123"), false)
    end)

    test.it("matches case sensitive by default", fun ()
        test.assert_eq(regex.match("hello", "Hello"), false)
    end)
end)

test.describe("regex.find", fun ()
    test.it("finds first match", fun ()
        test.assert_eq(regex.find("\\d+", "abc123def456"), "123")
    end)

    test.it("returns nil when no match", fun ()
        test.assert_nil(regex.find("\\d+", "abcdef"))
    end)

    test.it("finds word patterns", fun ()
        test.assert_eq(regex.find("\\w+", "hello world"), "hello")
    end)
end)

test.describe("regex.find_all", fun ()
    test.it("finds all matches", fun ()
        let matches = regex.find_all("\\d+", "abc123def456ghi789")
        test.assert_eq(matches.len(), 3)
        test.assert_eq(matches.get(0), "123")
        test.assert_eq(matches.get(1), "456")
        test.assert_eq(matches.get(2), "789")
    end)

    test.it("returns empty array when no matches", fun ()
        let matches = regex.find_all("\\d+", "abcdef")
        test.assert_eq(matches.len(), 0)
    end)

    test.it("finds all word patterns", fun ()
        let words = regex.find_all("\\w+", "hello brave new world")
        test.assert_eq(words.len(), 4)
    end)
end)

test.describe("regex.captures", fun ()
    test.it("captures groups", fun ()
        let caps = regex.captures("(\\w+)@(\\w+\\.\\w+)", "user@example.com")
        test.assert_eq(caps.len(), 3)
        test.assert_eq(caps.get(0), "user@example.com") # Full match
        test.assert_eq(caps.get(1), "user")
        test.assert_eq(caps.get(2), "example.com")
    end)

    test.it("returns nil when no match", fun ()
        test.assert_nil(regex.captures("\\d+", "abc"))
    end)

    test.it("captures date components", fun ()
        let caps = regex.captures("(\\d{4})-(\\d{2})-(\\d{2})", "2024-10-02")
        test.assert_eq(caps.get(1), "2024")
        test.assert_eq(caps.get(2), "10")
        test.assert_eq(caps.get(3), "02")
    end)
end)

test.describe("regex.captures_all", fun ()
    test.it("captures all matches with groups", fun ()
        let all = regex.captures_all("(\\d+)-(\\d+)", "10-20 and 30-40")
        test.assert_eq(all.len(), 2)

        let first = all.get(0)
        test.assert_eq(first.get(0), "10-20")
        test.assert_eq(first.get(1), "10")
        test.assert_eq(first.get(2), "20")

        let second = all.get(1)
        test.assert_eq(second.get(0), "30-40")
        test.assert_eq(second.get(1), "30")
        test.assert_eq(second.get(2), "40")
    end)

    test.it("returns empty array when no matches", fun ()
        let all = regex.captures_all("\\d+", "abc")
        test.assert_eq(all.len(), 0)
    end)
end)

test.describe("regex.replace", fun ()
    test.it("replaces first match", fun ()
        let result = regex.replace("\\d+", "abc123def456", "NUM")
        test.assert_eq(result, "abcNUMdef456")    end)

    test.it("returns original when no match", fun ()
        let result = regex.replace("\\d+", "abcdef", "NUM")
        test.assert_eq(result, "abcdef")    end)

    test.it("replaces with captured groups", fun ()
        let result = regex.replace("(\\w+)@(\\w+)", "user@example", "$2@$1")
        test.assert_eq(result, "example@user")    end)
end)

test.describe("regex.replace_all", fun ()
    test.it("replaces all matches", fun ()
        let result = regex.replace_all("\\d+", "abc123def456", "NUM")
        test.assert_eq(result, "abcNUMdefNUM")    end)

    test.it("replaces multiple occurrences", fun ()
        let result = regex.replace_all("o", "hello world", "0")
        test.assert_eq(result, "hell0 w0rld")    end)

    test.it("returns original when no match", fun ()
        let result = regex.replace_all("\\d+", "abcdef", "NUM")
        test.assert_eq(result, "abcdef")    end)
end)

test.describe("regex.split", fun ()
    test.it("splits by pattern", fun ()
        let parts = regex.split(",\\s*", "a, b, c, d")
        test.assert_eq(parts.len(), 4)
        test.assert_eq(parts.get(0), "a")
        test.assert_eq(parts.get(1), "b")
        test.assert_eq(parts.get(2), "c")
        test.assert_eq(parts.get(3), "d")
    end)

    test.it("splits by whitespace", fun ()
        let parts = regex.split("\\s+", "hello   world    foo")
        test.assert_eq(parts.len(), 3)
        test.assert_eq(parts.get(0), "hello")
        test.assert_eq(parts.get(1), "world")
        test.assert_eq(parts.get(2), "foo")
    end)

    test.it("splits by digits", fun ()
        let parts = regex.split("\\d+", "a123b456c")
        test.assert_eq(parts.len(), 3)
        test.assert_eq(parts.get(0), "a")
        test.assert_eq(parts.get(1), "b")
        test.assert_eq(parts.get(2), "c")
    end)
end)

test.describe("regex.is_valid", fun ()
    test.it("validates correct patterns", fun ()
        test.assert_eq(regex.is_valid("\\d+"), true)
        test.assert_eq(regex.is_valid("[a-z]+"), true)
        test.assert_eq(regex.is_valid("^hello$"), true)
    end)

    test.it("rejects invalid patterns", fun ()
        test.assert_eq(regex.is_valid("["), false)
        test.assert_eq(regex.is_valid("("), false)
        test.assert_eq(regex.is_valid("*"), false)
    end)

    test.it("validates complex patterns", fun ()
        test.assert_eq(regex.is_valid("\\w+@\\w+\\.\\w+"), true)
        test.assert_eq(regex.is_valid("\\d{3}-\\d{3}-\\d{4}"), true)
    end)
end)
