# Example settings file for Quest applications
# Copy this to .settings.toml and customize for your project

[os.environ]
QUEST_ENV = "development"
API_KEY = "your-api-key-here"
SECRET_KEY = "your-secret-key-here"

[app]
name = "My Quest Application"
version = "1.0.0"
debug = true
port = 3000
host = "127.0.0.1"

[database]
host = "localhost"
port = 5432
name = "myapp"
pool_size = 10
timeout = 30

[database.pool]
min_connections = 2
max_connections = 10
idle_timeout = 300

[cache]
enabled = true
ttl = 3600
type = "redis"

[cache.redis]
host = "localhost"
port = 6379
db = 0

[features]
enable_analytics = false
enable_uploads = true
max_upload_size = 10485760
allowed_formats = ["jpg", "png", "gif", "pdf"]

[logging]
level = "info"
format = "text"
outputs = ["stdout"]
colors = true

[server]
workers = 4
timeout = 30
max_request_size = 10485760
