[package]
name = "quest"
version = "0.1.0"
edition = "2021"

[dependencies]
pest = "2.7"
pest_derive = "2.7"
rustyline = "14.0"
term_size = "0.3"
md-5 = "0.10"
sha1 = "0.10"
sha2 = "0.10"
hmac = "0.12"
crc32fast = "1.4"
serde_json = "1.0"
glob = "0.3"
base64 = "0.22"
