services:
  postgres:
    image: postgres:17
    container_name: quest-postgres-test
    environment:
      POSTGRES_USER: quest
      POSTGRES_PASSWORD: quest_password
      POSTGRES_DB: quest_test
    ports:
      - "6432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quest"]
      interval: 5s
      timeout: 5s
      retries: 5

  mysql:
    image: mysql:9.1
    container_name: quest-mysql-test
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: quest_test
      MYSQL_USER: quest
      MYSQL_PASSWORD: quest_password
    ports:
      - "6603:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot_password"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  mysql_data:
