# Quest Project Configuration
name = "quest"
version = "0.1.0"
description = "A vibe coded scripting language focused on developer happiness."
authors = ["Claude Code", "Steven Osborn <steven@lolsborn.com>"]
license = "APACHE-2.0"
homepage = "https://github.com/lolsborn/quest"
repository = "https://github.com/lolsborn/quest"
keywords = ["programming-language", "interpreter", "repl"]

[scripts]
test = "scripts/qtest"
update = "cargo install --path ."
