# Quest Project Configuration
name = "quest"
version = "0.1.0"
description = "A vibe coded scripting language focused on developer happiness."
authors = ["Claude Code", "Steven Osborn <steven@lolsborn.com>"]
license = "APACHE-2.0"
homepage = "https://github.com/lolsborn/quest"
repository = "https://github.com/lolsborn/quest"
keywords = ["programming-language", "interpreter", "repl"]

[scripts]
test = "scripts/qtest test/"
update = "cargo install --path ."


# =========================================================================
#                    Module Configuration System (QEP-053)
# DO NOT put environment-specific or secret configuration here.
# Those belong in quest.local.toml
#
#    ┌─────────────────────────────────────────────────────────────┐
#    │                    Configuration Loading                    │
#    │                      (Last wins)                            │
#    ├─────────────────────────────────────────────────────────────┤
#    │                                                             │
#    │  1. quest.toml                                              │
#    │     └─> Base configuration (committed to git)               │
#    │         • Default values for all environments               │
#    │         • Shared configuration across team                  │
#    │         • Module-namespaced: [module.name]                  │
#    │                                                             │
#    │  2. quest.<env>.toml                                        │
#    │     └─> Environment-specific (committed to git)             │
#    │         • Development: quest.dev.toml                       │
#    │         • Staging: quest.staging.toml                       │
#    │         • Production: quest.prod.toml                       │
#    │         • Set via QUEST_ENV environment variable            │
#    │         • Overrides quest.toml values                       │
#    │                                                             │
#    │  3. quest.local.toml                                        │
#    │     └─> Local overrides (NOT committed, in .gitignore)      │
#    │         • Developer-specific configuration                  │
#    │         • Secrets and credentials                           │
#    │         • Overrides all previous files                      │
#    │                                                             │
#    └─────────────────────────────────────────────────────────────┘
#
# =========================================================================


# Standard Library Module Configurations
# Each module can declare its configuration schema and load from these sections

[std.test]
paths = ["./test"]       # Paths to search for tests
use_colors = true        # Enable colored output by default
use_condensed = true     # Enable condensed output by default
capture_output = "all"   # Output capture: all, no, 0, 1, stdout, stderr
filter_tags = []         # Only run tests with these tags
skip_tags = []           # Skip tests with these tags
